######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 5 10:42:02 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywidget.cpp model.cpp
SOURCES += model.cpp mywidget.cpp view.cpp
