######################################################################
# Automatically generated by qmake (2.01a) ?? ???? 5 17:17:39 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += EventList.h Note.h window.h WindowDialog.h
SOURCES += EventList.cpp main.cpp Note.cpp window.cpp WindowDialog.cpp
